apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-auth-service
  labels:
    k8s-app: demo-auth-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: demo-auth-service
  template:
    metadata:
      labels:
        k8s-app: demo-auth-service
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: auth-service
        image: auth-service:0.1
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
        volumeMounts:
        - name: jwt-key
          mountPath: "/tmp/"
          readOnly: true
      volumes:
      - name: jwt-key
        secret:
          secretName: auth-key
---
apiVersion: v1
kind: Service
metadata:
  name: demo-auth-service
  labels:
    k8s-app: demo-auth-service
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    k8s-app: demo-auth-service
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: auth-service
spec:
  rules:
    - host: demo-auth-service.kube.local
      http:
        paths:
          - path: /login
            backend:
              serviceName: demo-auth-service
              servicePort: 80
