apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-echo-service
  labels:
    k8s-app: demo-echo-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: demo-echo-service
  template:
    metadata:
      labels:
        k8s-app: demo-echo-service
    spec:
      terminationGracePeriodSeconds: 60
      initContainers:
      - name: init-networking
        image: auth-init:0.1
        imagePullPolicy: Never
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
          privileged: true
      containers:
      - name: proxy
        image: auth-proxy:0.1
        imagePullPolicy: Never
        ports:
          - containerPort: 8000
        volumeMounts:
        - name: jwt-key
          mountPath: "/tmp/"
          readOnly: true
      - name: echo-service
        image: echo-service:0.1
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
      volumes:
        - name: jwt-key
          secret:
            secretName: auth-pub

---
apiVersion: v1
kind: Service
metadata:
  name: demo-echo-service
  labels:
    k8s-app: demo-echo-service
  namespace: default
spec:
  clusterIP: None
  ports:
  - port: 80
    targetPort: 80
  selector:
    k8s-app: demo-echo-service
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: secure-demo-echo-service
  annotations:
    nginx.ingress.kubernetes.io/auth-url: http://demo-auth-service.default.svc.cluster.local
    nginx.ingress.kubernetes.io/auth-response-headers: X-JWT
    nginx.ingress.kubernetes.io/auth-signin: http://demo-auth-service.kube.local/login
  namespace: default
spec:
  rules:
  - host: secure-demo-echo-service.kube.local
    http:
      paths:
      - backend:
          serviceName: demo-echo-service
          servicePort: 80
        path: /
